version: '3'

services:
  mifadmin:
    build:
      context: ../
      dockerfile: ./docker/mifadmin/Dockerfile
      args:
        environment: ${environment}
        bucketName: ${bucketName}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
